header:
  license:
    spdx-id: BSD-3-Clause
    copyright-owner: Jupyter Development Team
    software-name: Jupyter-chat
    content: |
      Copyright (c) Jupyter Development Team.
      Distributed under the terms of the Modified BSD License.

  paths-ignore:
    - '**/*.typed'
    - '**/*.ipynb'
    - '**/*.json'
    - '**/*.md'
    - '**/*.svg'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/build'
    - '**/lib'
    - '**/node_modules'
    - '*.map.js'
    - '*.bundle.js'
    - '**/.*'
    - '**/binder/postBuild'
    - 'coverage'
    - 'LICENSE'
    - 'yarn.lock'
    - '**/_version.py'

  comment: on-failure
