# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: jupyter@googlegroups.com
author_name: Jupyter Development Team
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: server
labextension_name: jupyterlab-collaborative-chat-extension
mimetype: ''
mimetype_name: ''
project_short_description: A chat extension based on shared documents
python_name: jupyterlab_collaborative_chat
repository: https://github.com/jupyterlab/jupyter-chat
test: true
viewer_name: ''

