#!/usr/bin/env bash

# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

set -euxo pipefail

yarn || yarn

python -m pip install -vv -e . --no-build-isolation
jupyter server extension enable jupyter_collaboration

./scripts/install.sh collaborative

jupyter troubleshoot
jupyter notebook --show-config
jupyter lab --show-config
jupyter labextension list
jupyter server extension list
