#!/usr/bin/env bash

# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# Install chat extension
./scripts/dev_install.sh

jupyter troubleshoot
jupyter notebook --show-config
jupyter lab --show-config
jupyter labextension list
jupyter server extension list
